### ISSUE TITLE
Tests have long been disabled... and probably don't work?

### ISSUE THREAD

**Issue by rfay** [MurzNN/ddev-grafana#11]
Due to Github's timeout with no commits, the tests here haven't run for 7 months and are likely incompatible with current DDEV.

Are you still interested in maintaining this? 

If so, please consider
* Updating the tests.yml file to https://github.com/ddev/ddev-addon-template/blob/main/.github/workflows/tests.yml so that it doesn't time out any more.
* Getting the tests (or the add-on) working again.

If not, please consider removing the `ddev-get` label and probably update the README to say that it's no longer maintained. Or find another maintainer?

Thanks!
-Randy

**Comment by MurzNN** [comment]
Fixed tests to not stop running if the projects is not updated for the long time.

**Comment by rfay** [comment]
Thank you!
