### ISSUE TITLE
Please remove "ddev-get" label if this is not maintained or tested

### ISSUE THREAD

**Issue by rfay** [MurzNN/ddev-grafana#13]
Hi @MurzNN - It looks like maybe this add-on isn't maintained and the automated tests are not enabled, etc.

If it's not maintained, could you please remove the "ddev-get" topic from the repo so it's not discoverable?

Thanks,
-Randy

**Comment by MurzNN** [comment]
The tests were disabled automatically because the project had no new commits for a long time. Now I updated the GitHub workflow to keep them active, and released a new version with improved tests.
