### ISSUE TITLE
Github workflow updates

### ISSUE THREAD

**Issue by rfay** [MurzNN/ddev-grafana#6]
There are some things that can solve test problems:

* Update the usage of the keepalive workflow, see https://github.com/ddev/ddev-addon-template/blob/eba2da81ee29c2c8dfbfb84f9513a9354ec1405e/.github/workflows/tests.yml#L89-L91
* Add https://github.com/ddev/ddev-addon-template/blob/eba2da81ee29c2c8dfbfb84f9513a9354ec1405e/.github/workflows/tests.yml#L18-L20

**Comment by MurzNN** [comment]
Thanks, I've added this!
