### ISSUE TITLE
Grafana key rotation 

### ISSUE THREAD

**Issue by rfay** [MurzNN/ddev-grafana#8]
See https://grafana.com/blog/2023/08/24/grafana-security-update-gpg-signing-key-rotation/

I imagine it affects this project directly or indirectly.

**Comment by MurzNN** [comment]
Thank you for the informing! 

Seems that my case is not affected, regarding to:
> Who is not affected:
>    Users who have installed Grafana via a Docker image

But I'll lookup into it deeper.

**Comment by MurzNN** [comment]
Yeah, no needs to rotate it, so closing.
