### ISSUE TITLE
Unable to start @windows wsl

### ISSUE THREAD

**Issue by arsibux** [MurzNN/ddev-grafana#9]
Failed to start otel: ddev-router failed to become ready; debug with 'docker logs ddev-router'; logOutput=, err=health check timed out after 1m0s: labels map[com.docker.compose.service:ddev-router] timed out without becoming healthy, status=

![image](https://github.com/MurzNN/ddev-grafana/assets/9518132/2b6e5ef1-579c-4b6f-be67-3951d60ca0cb)

**Comment by rfay** [comment]
If you'd provide the output of `ddev debug test` as a file and look at the logs it would help understand what's going on.

**Comment by arsibux** [comment]
> If you'd provide the output of `ddev debug test` as a file and look at the logs it would help understand what's going on.

Thanks

**Comment by MurzNN** [comment]
Closing as outdated. If still actual - please add debug info and reopen.
